[package]
name = "pixel-receiver-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.0", features = ["derive"] }
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
image = "0.25"
pixels = "0.13"
winit = { version = "0.30", features = ["rwh_05"] }
log = "0.4"
raw-window-handle = "0.6"
env_logger = "0.11"
